name: Complete CI pipeline

on: workflow_dispatch

jobs:
  sonar:
    runs-on: [self-hosted, wsl-pvk]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=NodeJS_App
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker:
    runs-on: [self-hosted, wsl-pvk]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -f Dockerfile.distroless -t dockerfile-distroless .

      - name : Set Docker tag
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Tag Docker image
        run: docker tag dockerfile-distroless ${{ vars.DOCKERHUB_USERNAME }}/nodeapp:$SHORT_SHA

      - name: Push Image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/nodeapp:$SHORT_SHA
