name: Demo pipeline

on:
  workflow_dispatch: 
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  demo123:
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Print some statement
        run: echo "Runner working successfully"
