name: CI pipeline

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  pull_request: 
    branches: [main]

jobs:
  sonar:
    runs-on: [self-hosted, Linux]
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=NodeJsApp
            -Dsonar.sources=.
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: [self-hosted, Linux]
    # needs: sonar   # runs only if sonar succeeds
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.distroless -t dockerfile-distroless .

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          docker tag dockerfile-distroless ${{ secrets.DOCKER_USERNAME }}/nodeapp:$SHORT_SHA

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodeapp:$SHORT_SHA
